### PR TITLE
fetch upstream changes

### PR DESCRIPTION
**Pull request by iamtalhaasghar**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by iamtalhaasghar** [comment]
a new version of synapse [v1.107.0](https://github.com/element-hq/synapse/releases/tag/v1.107.0)  has been released which has two interesting features:

1. account suspension
2. account locking

We should merge the upstream changes and test this out in a staging server. @kashif-liaqat @kashif-umair

**Comment by kashif-umair** [comment]
We need to create a separate branch and pull upstream changes in that branch. This is so that we can pull that branch to run on our staging server

**Comment by iamtalhaasghar** [comment]
Pls merge this PR and then lets create a new branch from that point and we can then do test latest code there

**Review by MuhammadSaadSiddique — APPROVED** [review]
Approving on demand of Talha

**Review by MohammadOwaisData — APPROVED** [review]

**Pull request merged**
